-- To'Latino — in-app notifications. A per-user feed auto-generated by DB triggers
-- on the real events (orders, bookings, rentals, chat messages) so both the buyer
-- and the seller get alerted the moment something happens. Language-neutral: rows
-- store a `kind` + `data` jsonb and the client renders the localized text (es/en).
-- Realtime-enabled → the bell updates live. This table is also the natural queue a
-- future Edge Function reads to fan out Web Push / email. Idempotent. Apply: paste
-- into the Supabase SQL Editor + Run.

create table if not exists public.notifications (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users(id) on delete cascade,
  kind       text not null,               -- order_new | order_status | booking_new | booking_status | rental_new | rental_status | message
  data       jsonb not null default '{}', -- render inputs (code, total, status, name, preview…)
  link       text,                         -- where tapping goes (/cuenta | /negocio)
  read       boolean not null default false,
  created_at timestamptz not null default now()
);
create index if not exists notifications_user_idx on public.notifications (user_id, created_at desc);

alter table public.notifications enable row level security;
-- the user reads / marks read their OWN notifications; only triggers (definer) insert.
drop policy if exists "own notifications read" on public.notifications;
create policy "own notifications read" on public.notifications for select using (user_id = auth.uid());
drop policy if exists "own notifications update" on public.notifications;
create policy "own notifications update" on public.notifications for update using (user_id = auth.uid()) with check (user_id = auth.uid());

-- helper: insert a notification (no-op when the recipient is null)
create or replace function public.notify_user(in_user uuid, in_kind text, in_data jsonb, in_link text)
returns void language sql security definer set search_path = public as $$
  insert into public.notifications (user_id, kind, data, link)
  select in_user, in_kind, in_data, in_link where in_user is not null;
$$;

-- orders: new → owner; status change → customer
create or replace function public.tg_notify_order() returns trigger language plpgsql security definer set search_path = public as $$
declare v_owner uuid;
begin
  select owner_id into v_owner from public.businesses where id = new.business_id;
  if tg_op = 'INSERT' then
    perform public.notify_user(v_owner, 'order_new', jsonb_build_object('code', new.code, 'total', new.total, 'channel', new.channel), '/negocio');
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    perform public.notify_user(new.user_id, 'order_status', jsonb_build_object('code', new.code, 'status', new.status), '/cuenta');
  end if;
  return new;
end $$;
drop trigger if exists trg_notify_order on public.business_orders;
create trigger trg_notify_order after insert or update on public.business_orders for each row execute function public.tg_notify_order();

-- bookings: new → owner; status change → customer
create or replace function public.tg_notify_booking() returns trigger language plpgsql security definer set search_path = public as $$
declare v_owner uuid;
begin
  select owner_id into v_owner from public.businesses where id = new.business_id;
  if tg_op = 'INSERT' then
    perform public.notify_user(v_owner, 'booking_new', jsonb_build_object('service', new.service_name, 'name', new.customer_name), '/negocio');
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    perform public.notify_user(new.user_id, 'booking_status', jsonb_build_object('service', new.service_name, 'status', new.status), '/cuenta');
  end if;
  return new;
end $$;
drop trigger if exists trg_notify_booking on public.business_bookings;
create trigger trg_notify_booking after insert or update on public.business_bookings for each row execute function public.tg_notify_booking();

-- rentals: new → owner; status change → customer
create or replace function public.tg_notify_rental() returns trigger language plpgsql security definer set search_path = public as $$
declare v_owner uuid;
begin
  select owner_id into v_owner from public.businesses where id = new.business_id;
  if tg_op = 'INSERT' then
    perform public.notify_user(v_owner, 'rental_new', jsonb_build_object('item', new.item_name, 'name', new.customer_name), '/negocio');
  elsif tg_op = 'UPDATE' and new.status is distinct from old.status then
    perform public.notify_user(new.user_id, 'rental_status', jsonb_build_object('item', new.item_name, 'status', new.status), '/cuenta');
  end if;
  return new;
end $$;
drop trigger if exists trg_notify_rental on public.business_rentals;
create trigger trg_notify_rental after insert or update on public.business_rentals for each row execute function public.tg_notify_rental();

-- chat: notify the recipient (owner ← customer msg, customer ← owner msg)
create or replace function public.tg_notify_message() returns trigger language plpgsql security definer set search_path = public as $$
declare v_biz uuid; v_customer uuid; v_cname text; v_owner uuid; v_bname text;
begin
  select c.business_id, c.customer_user_id, c.customer_name into v_biz, v_customer, v_cname
    from public.business_conversations c where c.id = new.conversation_id;
  select owner_id, name into v_owner, v_bname from public.businesses where id = v_biz;
  if new.from_owner then
    perform public.notify_user(v_customer, 'message', jsonb_build_object('name', v_bname, 'preview', left(new.body, 80)), '/cuenta');
  else
    perform public.notify_user(v_owner, 'message', jsonb_build_object('name', coalesce(v_cname, 'Cliente'), 'preview', left(new.body, 80)), '/negocio');
  end if;
  return new;
end $$;
drop trigger if exists trg_notify_message on public.business_messages;
create trigger trg_notify_message after insert on public.business_messages for each row execute function public.tg_notify_message();

-- realtime → the bell updates live
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications') then
    alter publication supabase_realtime add table public.notifications;
  end if;
end $$;

notify pgrst, 'reload schema';
