'use client';

// In-app notifications (migration 0054). A per-user feed auto-generated by DB
// triggers on real events (orders, bookings, rentals, chat). Signed in → real
// rows + realtime; logged out → the demo fixtures so the prototype stays alive.
// Rows are language-neutral (kind + data); the localized text is built here as a
// bilingual tuple the bell/panel render via L. Consumed by NotifPanel + the bell
// badge (AppHeader / BottomNav).

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { useLang } from '@/lib/i18n';
import { syncPush } from '@/lib/push';

export type NotifIcon = 'heart' | 'message' | 'calendar' | 'store' | 'user' | 'tag' | 'star';
export type NotifItem = {
  id: string;
  icon: NotifIcon;
  color: string;
  bg: string;
  title: [string, string]; // [es, en]
  sub: [string, string];
  group: 'hoy' | 'semana' | 'antes';
  time: [string, string];
  read: boolean;
  link: string;
};

type RawRow = { id: string; kind: string; data: Record<string, unknown>; link: string | null; read: boolean; created_at: string };

const META: Record<string, { icon: NotifIcon; color: string; bg: string }> = {
  order_new: { icon: 'store', color: '#C4144C', bg: '#FFECF2' },
  order_status: { icon: 'store', color: '#007A57', bg: '#E6FAF3' },
  booking_new: { icon: 'calendar', color: '#C4144C', bg: '#FFECF2' },
  booking_status: { icon: 'calendar', color: '#007A57', bg: '#E6FAF3' },
  booking_cancelled: { icon: 'calendar', color: '#E11D48', bg: '#FFECF2' },
  booking_resched: { icon: 'calendar', color: '#8A5A00', bg: '#FFF6E3' },
  rental_new: { icon: 'tag', color: '#C4144C', bg: '#FFECF2' },
  rental_status: { icon: 'tag', color: '#007A57', bg: '#E6FAF3' },
  ticket_new: { icon: 'calendar', color: '#C4144C', bg: '#FFECF2' },
  ticket_status: { icon: 'calendar', color: '#007A57', bg: '#E6FAF3' },
  review_new: { icon: 'star', color: '#8A5A00', bg: '#FFF6E3' },
  review_reply: { icon: 'message', color: '#007A57', bg: '#E6FAF3' },
  endorse_new: { icon: 'heart', color: '#FF2D6F', bg: '#FFECF2' },
  rsvp_new: { icon: 'user', color: '#C4144C', bg: '#FFECF2' },
  event_cancelled: { icon: 'calendar', color: '#E11D48', bg: '#FFECF2' },
  waitlist_open: { icon: 'calendar', color: '#007A57', bg: '#E6FAF3' },
  message: { icon: 'message', color: '#0072B6', bg: '#DEF4FF' },
  // Comunidad (migración 0136). Hasta 2026-08-03 la sección era muda: te
  // comentaban o te seguían y nadie te avisaba.
  comment_new: { icon: 'message', color: '#C4144C', bg: '#FFECF2' },
  reply_new: { icon: 'message', color: '#0072B6', bg: '#DEF4FF' },
  post_like: { icon: 'heart', color: '#E11D48', bg: '#FFECF2' },
  follow_new: { icon: 'user', color: '#007A57', bg: '#E6FAF3' },
  // Cuenta, plan, reclamos y dinero (0121/0122). La base los emitía desde hacía
  // meses y la campana los pintaba como «Notificación» sin una línea de texto.
  account_suspended: { icon: 'user', color: '#E11D48', bg: '#FFECF2' },
  account_restored: { icon: 'user', color: '#007A57', bg: '#E6FAF3' },
  business_tier_changed: { icon: 'store', color: '#8A5A00', bg: '#FFF6E3' },
  order_status_admin: { icon: 'store', color: '#0072B6', bg: '#DEF4FF' },
  purchase_fulfilled: { icon: 'store', color: '#007A57', bg: '#E6FAF3' },
  purchase_refunded: { icon: 'tag', color: '#8A5A00', bg: '#FFF6E3' },
  claim_opened: { icon: 'message', color: '#E11D48', bg: '#FFECF2' },
  claim_message: { icon: 'message', color: '#0072B6', bg: '#DEF4FF' },
  claim_resuelto: { icon: 'message', color: '#007A57', bg: '#E6FAF3' },
  claim_rechazado: { icon: 'message', color: '#E11D48', bg: '#FFECF2' },
  // Dealer de carros (0119) y Bienes raíces (0117) — avisos para el dueño.
  auto_lead: { icon: 'user', color: '#C4144C', bg: '#FFECF2' },
  auto_test: { icon: 'calendar', color: '#C4144C', bg: '#FFECF2' },
  re_lead: { icon: 'user', color: '#C4144C', bg: '#FFECF2' },
  re_tour: { icon: 'calendar', color: '#C4144C', bg: '#FFECF2' },
};
// Qué cosa se compró / se reclama, en palabras. La base manda claves distintas
// según de dónde venga (`payments.kind` en inglés, los reclamos en español).
const COSA: Record<string, [string, string]> = {
  order: ['tu pedido', 'your order'], orden: ['tu pedido', 'your order'],
  booking: ['tu reserva', 'your booking'], reserva: ['tu reserva', 'your booking'],
  rental: ['tu renta', 'your rental'], renta: ['tu renta', 'your rental'],
  ticket: ['tu boleto', 'your ticket'], boleto: ['tu boleto', 'your ticket'],
  otro: ['tu compra', 'your purchase'],
};
const cosa = (v: unknown): [string, string] => COSA[String(v)] ?? ['tu compra', 'your purchase'];
const STATUS: Record<string, [string, string]> = {
  new: ['nuevo', 'new'], preparing: ['en preparación', 'preparing'], ready: ['listo', 'ready'],
  completed: ['completado', 'completed'], cancelled: ['cancelado', 'cancelled'],
  pending: ['pendiente', 'pending'], confirmed: ['confirmado', 'confirmed'], seated: ['en curso', 'in progress'],
  done: ['completado', 'done'], out: ['entregado', 'handed out'], returned: ['devuelto', 'returned'],
  used: ['usado', 'used'], refunded: ['reembolsado', 'refunded'], no_show: ['no asistió', 'no-show'],
};
const money = (v: unknown) => (v == null ? '' : `$${Number(v).toFixed(2)}`);
const st = (v: unknown): [string, string] => STATUS[String(v)] ?? [String(v ?? ''), String(v ?? '')];
/** Fecha+hora corta y bilingüe para las citas que llegan por aviso. */
const cuando = (v: unknown): [string, string] => {
  const t = v ? new Date(String(v)) : null;
  if (!t || Number.isNaN(t.getTime())) return ['', ''];
  const o: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short', hour: 'numeric', minute: '2-digit' };
  return [t.toLocaleString('es-US', o), t.toLocaleString('en-US', o)];
};

function kindText(kind: string, d: Record<string, unknown>): { title: [string, string]; sub: [string, string] } {
  const s = (k: string) => String(d[k] ?? '');
  switch (kind) {
    case 'order_new': return { title: ['Nuevo pedido', 'New order'], sub: [`${s('code')} · ${money(d.total)}`.trim(), `${s('code')} · ${money(d.total)}`.trim()] };
    case 'order_status': {
      const from = [s('business') || s('code'), s('business') || s('code')] as [string, string];
      // STORE orders (Tienda — fulfillment.kind='store') speak Amazon: packing,
      // truck, "ready for store pickup". Food keeps the DoorDash voice.
      const store = d.kind === 'store';
      if (d.dispatch === 'assigned') return { title: ['Repartidor asignado a tu pedido', 'A driver was assigned to your order'], sub: from };
      if (d.dispatch === 'picked_up') return { title: [`${s('driver') || 'El repartidor'} recogió tu pedido`, `${s('driver') || 'Your driver'} picked up your order`], sub: from };
      if (d.dispatch === 'on_the_way') return store
        ? { title: ['¡Tu pedido va en camino! 🚚', 'Your order is on the way! 🚚'], sub: from }
        : { title: ['¡Tu pedido va en camino! 🛵', 'Your order is on the way! 🛵'], sub: from };
      if (d.dispatch === 'delivered') return { title: ['Tu pedido fue entregado ✅', 'Your order was delivered ✅'], sub: from };
      const [a, b] = st(d.status);
      if (d.status === 'preparing') return store
        ? { title: ['El negocio confirmó tu compra y está empacando tu pedido 📦', 'The business confirmed your purchase and is packing your order 📦'], sub: from }
        : { title: ['El negocio aceptó tu pedido y lo está preparando', 'The business accepted your order and is preparing it'], sub: from };
      if (d.status === 'ready') return store && d.channel !== 'delivery'
        ? { title: ['Tu pedido está listo para recoger en tienda 🛍️', 'Your order is ready for store pickup 🛍️'], sub: from }
        : { title: ['Tu pedido está listo 🎉', 'Your order is ready 🎉'], sub: from };
      return { title: [`Tu pedido está ${a}`, `Your order is ${b}`], sub: from };
    }
    case 'booking_new': {
      const who = [s('service'), s('name')].filter(Boolean).join(' · ');
      // pending → needs the owner's approval; confirmed → auto-confirmed booking
      return d.status === 'pending'
        ? { title: ['Nueva solicitud de cita 📅', 'New booking request 📅'], sub: [who, who] }
        : { title: ['Nueva reserva 📅', 'New booking 📅'], sub: [who, who] };
    }
    case 'booking_status': {
      const svc = [s('service'), s('service')] as [string, string];
      if (d.status === 'confirmed') return { title: ['¡Tu cita está confirmada! 📅', 'Your appointment is confirmed! 📅'], sub: svc };
      if (d.status === 'cancelled') return { title: ['Tu cita fue cancelada', 'Your appointment was cancelled'], sub: svc };
      if (d.status === 'no_show') return { title: ['Se marcó que no asististe a tu cita', 'You were marked as a no-show'], sub: svc };
      if (d.status === 'seated') return { title: ['Tu cita está en curso', 'Your appointment is in progress'], sub: svc };
      if (d.status === 'done') return { title: ['¡Gracias por tu visita! ⭐', 'Thanks for coming in! ⭐'], sub: svc };
      const [a, b] = st(d.status);
      return { title: [`Tu reserva está ${a}`, `Your booking is ${b}`], sub: svc };
    }
    case 'review_new': {
      // owner-facing: a customer left a review. sub = "N★ · Name"
      const stars = '★'.repeat(Math.max(1, Math.min(5, Number(d.rating) || 5)));
      const who = [`${stars} · ${s('name')}`, `${stars} · ${s('name')}`] as [string, string];
      return { title: ['Nueva reseña ⭐', 'New review ⭐'], sub: who };
    }
    case 'review_reply': {
      // customer-facing: the business responded to their review
      const biz = [s('business'), s('business')] as [string, string];
      return { title: ['Respondieron tu reseña 💬', 'Your review got a reply 💬'], sub: biz };
    }
    case 'booking_cancelled': {
      const who = [s('service'), s('name')].filter(Boolean).join(' · ');
      return { title: ['Reserva cancelada por el cliente', 'Booking cancelled by the client'], sub: [who, who] };
    }
    case 'booking_resched': {
      const who = [s('service'), s('name')].filter(Boolean).join(' · ');
      return { title: ['El cliente reagendó su cita', 'The client rescheduled their appointment'], sub: [who, who] };
    }
    case 'rental_new': {
      const n = Number(d.count) || 1;
      const what = n > 1 ? `${s('item')} +${n - 1} · ${s('name')}` : `${s('item') || s('name')}`;
      return d.status === 'pending'
        ? { title: ['Nueva solicitud de renta 📦', 'New rental request 📦'], sub: [what, what] }
        : { title: ['Nueva renta 📦', 'New rental 📦'], sub: [what, what] };
    }
    case 'rental_status': { const [a, b] = st(d.status); return { title: [`Tu renta está ${a}`, `Your rental is ${b}`], sub: [s('item'), s('item')] }; }
    case 'endorse_new': return { title: ['Nueva recomendación 👍', 'New recommendation 👍'], sub: [`${s('name')} te recomendó`, `${s('name')} recommended you`] };
    case 'ticket_new': return { title: ['Boletos vendidos', 'Tickets sold'], sub: [`${s('event')} · ${s('qty')} · ${s('name')}`, `${s('event')} · ${s('qty')} · ${s('name')}`] };
    case 'ticket_status': { const [a, b] = st(d.status); return { title: [`Tu boleto: ${a}`, `Your ticket: ${b}`], sub: [s('event'), s('event')] }; }
    case 'rsvp_new': return { title: ['Nuevo asistente', 'New attendee'], sub: [s('event'), s('event')] };
    case 'event_cancelled': return { title: ['Evento cancelado', 'Event cancelled'], sub: [s('event'), s('event')] };
    case 'waitlist_open': return { title: ['¡Se liberó un lugar!', 'A spot opened up!'], sub: [s('event'), s('event')] };
    case 'message': return { title: [`Mensaje de ${s('name')}`, `Message from ${s('name')}`], sub: [s('preview') || 'Toca para leerlo', s('preview') || 'Tap to read it'] };
    // ── Comunidad ──
    case 'comment_new': return { title: [`${s('name')} comentó tu publicación`, `${s('name')} commented on your post`], sub: [s('preview') || 'Toca para leerlo', s('preview') || 'Tap to read it'] };
    case 'reply_new':   return { title: [`${s('name')} te respondió`, `${s('name')} replied to you`], sub: [s('preview') || 'Toca para leerlo', s('preview') || 'Tap to read it'] };
    case 'post_like':   return { title: [`A ${s('name')} le gustó tu publicación`, `${s('name')} liked your post`], sub: [s('preview') || 'Tu publicación', s('preview') || 'Your post'] };
    case 'follow_new':  return { title: [`${s('name')} te sigue`, `${s('name')} is following you`], sub: ['Ahora ve tus publicaciones en su inicio', 'They now see your posts in their feed'] };
    // ── Cuenta y plan ──
    case 'account_suspended': {
      const [d1, e1] = cuando(d.until);
      const hasta: [string, string] = d.until
        ? [`Hasta el ${d1}${s('reason') ? ` · ${s('reason')}` : ''}`, `Until ${e1}${s('reason') ? ` · ${s('reason')}` : ''}`]
        : [s('reason') || 'Escríbenos si crees que fue un error', s('reason') || 'Contact us if you think this was a mistake'];
      return { title: ['Tu cuenta quedó suspendida', 'Your account was suspended'], sub: hasta };
    }
    case 'account_restored':
      return { title: ['Tu cuenta volvió a estar activa ✅', 'Your account is active again ✅'], sub: ['Ya puedes publicar y comprar como siempre', 'You can post and buy again as usual'] };
    case 'business_tier_changed': {
      const biz = s('business');
      return { title: [`Tu negocio pasó al plan ${s('tier')}`, `Your business moved to the ${s('tier')} plan`], sub: [biz, biz] };
    }
    // ── Dinero y reclamos ──
    case 'order_status_admin': {
      const [q, w] = cosa(d.kind);
      const [a, b] = st(d.status);
      return { title: [`Soporte actualizó ${q}`, `Support updated ${w}`], sub: [`${s('code')} · ${a}`.trim(), `${s('code')} · ${b}`.trim()] };
    }
    case 'purchase_fulfilled': {
      const [q, w] = cosa(d.kind);
      return { title: ['Tu compra ya quedó registrada ✅', 'Your purchase went through ✅'], sub: [`Ya puedes ver ${q} en tu cuenta`, `You can now see ${w} in your account`] };
    }
    case 'purchase_refunded': {
      const [q, w] = cosa(d.kind);
      const por = s('reason');
      return { title: [`Te reembolsamos ${q}`, `We refunded ${w}`], sub: [`${s('code')}${por ? ` · ${por}` : ''}`.trim(), `${s('code')}${por ? ` · ${por}` : ''}`.trim()] };
    }
    case 'claim_opened': {
      const [q, w] = cosa(d.kind);
      return { title: ['Un cliente abrió un reclamo', 'A customer opened a claim'], sub: [`${s('code')} · sobre ${q}`, `${s('code')} · about ${w}`] };
    }
    case 'claim_message':
      return { title: ['Nuevo mensaje en tu reclamo 💬', 'New message on your claim 💬'], sub: [s('code'), s('code')] };
    case 'claim_resuelto':
      return { title: ['Tu reclamo se resolvió ✅', 'Your claim was resolved ✅'], sub: [s('resolution') || s('code'), s('resolution') || s('code')] };
    case 'claim_rechazado':
      return { title: ['Tu reclamo fue rechazado', 'Your claim was declined'], sub: [s('resolution') || s('code'), s('resolution') || s('code')] };
    // ── Dealer de carros ──
    case 'auto_lead': {
      const v = s('vehicle');
      const quien: [string, string] = [`${s('name')}${v ? ` · ${v}` : ''}`, `${s('name')}${v ? ` · ${v}` : ''}`];
      if (d.kind === 'oferta') return { title: ['Recibiste una oferta por un carro 💵', 'You got an offer on a car 💵'], sub: quien };
      if (d.kind === 'prequal') return { title: ['Alguien pidió precalificar un crédito', 'Someone asked to get pre-qualified'], sub: quien };
      if (d.kind === 'prueba') return { title: ['Alguien quiere una prueba de manejo 🚗', 'Someone wants a test drive 🚗'], sub: quien };
      return { title: ['Nuevo interesado en un carro 🚗', 'New lead on a car 🚗'], sub: quien };
    }
    case 'auto_test': {
      const [d1, e1] = cuando(d.at);
      return { title: ['Prueba de manejo agendada 🚗', 'Test drive booked 🚗'], sub: [`${s('vehicle')} · ${d1}`.trim(), `${s('vehicle')} · ${e1}`.trim()] };
    }
    // ── Bienes raíces ──
    case 're_lead': {
      const pr = s('property');
      const quien: [string, string] = [`${s('name')}${pr ? ` · ${pr}` : ''}`, `${s('name')}${pr ? ` · ${pr}` : ''}`];
      if (d.kind === 'oferta') return { title: [`Recibiste una oferta${d.offer ? ` de ${money(d.offer)}` : ''} 💵`, `You got an offer${d.offer ? ` of ${money(d.offer)}` : ''} 💵`], sub: quien };
      if (d.kind === 'solicitud') return { title: ['Nueva solicitud de renta 🏠', 'New rental application 🏠'], sub: quien };
      return { title: ['Nuevo interesado en una propiedad 🏠', 'New lead on a property 🏠'], sub: quien };
    }
    case 're_tour': {
      const [d1, e1] = cuando(d.at);
      const video = d.mode === 'video';
      return {
        title: video ? ['Visita por video agendada 🏠', 'Video tour booked 🏠'] : ['Visita agendada 🏠', 'Tour booked 🏠'],
        sub: [`${s('property')} · ${d1}`.trim(), `${s('property')} · ${e1}`.trim()],
      };
    }
    default: return { title: ['Notificación', 'Notification'], sub: ['', ''] };
  }
}
function relTime(iso: string): [string, string] {
  const min = Math.floor((Date.now() - new Date(iso).getTime()) / 60000);
  if (min < 1) return ['ahora', 'now'];
  if (min < 60) return [`hace ${min} min`, `${min}m`];
  const h = Math.floor(min / 60);
  if (h < 24) return [`hace ${h} h`, `${h}h`];
  const dd = Math.floor(h / 24);
  if (dd === 1) return ['ayer', '1d'];
  return [`hace ${dd} d`, `${dd}d`];
}
function groupOf(iso: string): 'hoy' | 'semana' | 'antes' {
  const d = (Date.now() - new Date(iso).getTime()) / 86400000;
  return d < 1 ? 'hoy' : d < 7 ? 'semana' : 'antes';
}
// Muchos títulos acaban en un emoji. En un teléfono de 390px el título parte en
// dos líneas y el emoji se queda SOLO en la de abajo, que se lee como un fallo.
// Se pega a la última palabra con un espacio duro. Aquí, una vez, en vez de en
// cada uno de los 33 textos (y vale para los que vengan).
const pegarEmoji = (s: string) => s.replace(/\s+(\p{Extended_Pictographic}\uFE0F?)$/u, '\u00A0$1');
const rowToItem = (r: RawRow, read: boolean): NotifItem => {
  const m = META[r.kind] ?? { icon: 'store', color: '#C4144C', bg: '#FFECF2' };
  const t = kindText(r.kind, r.data ?? {});
  return {
    id: r.id, icon: m.icon, color: m.color, bg: m.bg,
    title: [pegarEmoji(t.title[0]), pegarEmoji(t.title[1])],
    sub: t.sub, group: groupOf(r.created_at), time: relTime(r.created_at), read, link: r.link || '/cuenta',
  };
};

type Ctx = {
  items: NotifItem[]; unreadCount: number; demo: boolean;
  /** La consulta falló (no es lo mismo que «no tienes avisos»). */
  failed: boolean;
  /** Hay más de los que se han traído: la insignia usa el total real. */
  hasMore: boolean;
  loadingMore: boolean;
  loadMore: () => void;
  markRead: (id: string) => void; markAllRead: () => void;
};
/** Cuántas se traen por página. Antes eran 60 fijas y no había forma de ver la 61. */
const PAGE = 40;

const NotifCtx = createContext<Ctx | null>(null);

export function NotificationsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const { lang } = useLang();
  const [rows, setRows] = useState<RawRow[] | null>(null); // null → demo (logged out)
  const [readSet, setReadSet] = useState<Set<string>>(new Set());
  // Un fallo de la consulta NO es una campana vacía. Antes se descartaba el
  // `error` y «no se pudo cargar» se pintaba igual que «todo al día» — el
  // usuario se quedaba sin saber que le habían escrito. (2ª auditoría.)
  const [failed, setFailed] = useState(false);
  // El total REAL de no leídos, contado en la base. La insignia se calculaba
  // sobre las 60 traídas: con 119 sin leer, decía 57.
  const [unreadTotal, setUnreadTotal] = useState(0);
  const [total, setTotal] = useState(0);
  const [loadingMore, setLoadingMore] = useState(false);

  // If this device already granted push, refresh its stored subscription on login
  // (endpoints rotate) so send-push keeps reaching it. Silent no-op otherwise.
  useEffect(() => { if (user) void syncPush(lang); }, [user?.id, lang]);

  // load + realtime for the signed-in user
  useEffect(() => {
    if (!user || !supabase) { setRows(null); setReadSet(new Set()); setFailed(false); return; }
    let cancelled = false;
    setFailed(false);
    void (async () => {
      const [page, unread, all] = await Promise.all([
        supabase!.from('notifications').select('id,kind,data,link,read,created_at')
          .eq('user_id', user.id).order('created_at', { ascending: false }).limit(PAGE),
        supabase!.from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', user.id).eq('read', false),
        supabase!.from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', user.id),
      ]);
      if (cancelled) return;
      if (page.error) { setFailed(true); setRows([]); return; }
      setRows((page.data as RawRow[]) ?? []);
      setUnreadTotal(unread.count ?? 0);
      setTotal(all.count ?? 0);
    })();
    const ch = supabase
      .channel(`notif-${user.id}`)
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'notifications', filter: `user_id=eq.${user.id}` },
        (payload) => setRows((l) => {
          const r = payload.new as RawRow;
          if (l && l.some((x) => x.id === r.id)) return l;
          setUnreadTotal((n) => n + 1);
          setTotal((n) => n + 1);
          return [r, ...(l ?? [])];
        }))
      .subscribe();
    return () => { cancelled = true; supabase!.removeChannel(ch); };
  }, [user?.id]);

  const items = useMemo<NotifItem[]>(() => {
    // Real notifications only. Guests / not-yet-loaded state = empty (never the
    // NOTIFS demo fixtures presented as real, with a fake unread badge — rule #8).
    if (rows) return rows.map((r) => rowToItem(r, r.read || readSet.has(r.id)));
    return [];
  }, [rows, readSet]);

  // El total sale de la base; se le restan los que se han marcado leídos en esta
  // sesión y que ya estaban traídos.
  const leidosAhora = items.filter((i) => readSet.has(i.id) && !rows?.find((r) => r.id === i.id)?.read).length;
  const unreadCount = Math.max(0, unreadTotal - leidosAhora);
  const hasMore = !!rows && rows.length < total;

  const loadMore = useCallback(() => {
    if (!user || !supabase || !rows || loadingMore) return;
    setLoadingMore(true);
    void supabase.from('notifications').select('id,kind,data,link,read,created_at')
      .eq('user_id', user.id).order('created_at', { ascending: false })
      .range(rows.length, rows.length + PAGE - 1)
      .then(({ data, error }) => {
        setLoadingMore(false);
        if (error || !Array.isArray(data)) return;
        setRows((l) => {
          const vistos = new Set((l ?? []).map((x) => x.id));
          return [...(l ?? []), ...(data as RawRow[]).filter((r) => !vistos.has(r.id))];
        });
      });
  }, [user, rows, loadingMore]);

  const markRead = useCallback((id: string) => {
    setReadSet((s) => new Set(s).add(id));
    if (user && supabase && rows) supabase.from('notifications').update({ read: true }).eq('id', id).then(() => {});
  }, [user, rows]);
  const markAllRead = useCallback(() => {
    setReadSet(new Set(items.map((i) => i.id)));
    setUnreadTotal(0);
    if (user && supabase && rows) supabase.from('notifications').update({ read: true }).eq('user_id', user.id).eq('read', false).then(() => {});
  }, [user, rows, items]);

  const value = useMemo<Ctx>(
    () => ({ items, unreadCount, demo: !rows, failed, hasMore, loadingMore, loadMore, markRead, markAllRead }),
    [items, unreadCount, rows, failed, hasMore, loadingMore, loadMore, markRead, markAllRead],
  );
  return <NotifCtx.Provider value={value}>{children}</NotifCtx.Provider>;
}

export function useNotifications(): Ctx {
  const ctx = useContext(NotifCtx);
  if (!ctx) throw new Error('useNotifications must be used inside <NotificationsProvider>');
  return ctx;
}
