'use client';

// In-app notifications (migration 0054). A per-user feed auto-generated by DB
// triggers on real events (orders, bookings, rentals, chat). Signed in → real
// rows + realtime; logged out → the demo fixtures so the prototype stays alive.
// Rows are language-neutral (kind + data); the localized text is built here as a
// bilingual tuple the bell/panel render via L. Consumed by NotifPanel + the bell
// badge (AppHeader / BottomNav).

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { NOTIFS, VIEW_PATH } from '@/data/fixtures';

export type NotifIcon = 'heart' | 'message' | 'calendar' | 'store' | 'user' | 'tag';
export type NotifItem = {
  id: string;
  icon: NotifIcon;
  color: string;
  bg: string;
  title: [string, string]; // [es, en]
  sub: [string, string];
  group: 'hoy' | 'semana' | 'antes';
  time: [string, string];
  read: boolean;
  link: string;
};

type RawRow = { id: string; kind: string; data: Record<string, unknown>; link: string | null; read: boolean; created_at: string };

const META: Record<string, { icon: NotifIcon; color: string; bg: string }> = {
  order_new: { icon: 'store', color: '#6D4DF6', bg: '#EFEBFF' },
  order_status: { icon: 'store', color: '#1F8A4C', bg: '#E3F5EA' },
  booking_new: { icon: 'calendar', color: '#6D4DF6', bg: '#EFEBFF' },
  booking_status: { icon: 'calendar', color: '#1F8A4C', bg: '#E3F5EA' },
  rental_new: { icon: 'tag', color: '#6D4DF6', bg: '#EFEBFF' },
  rental_status: { icon: 'tag', color: '#1F8A4C', bg: '#E3F5EA' },
  message: { icon: 'message', color: '#2F6FED', bg: '#E5EFFB' },
};
const STATUS: Record<string, [string, string]> = {
  new: ['nuevo', 'new'], preparing: ['en preparación', 'preparing'], ready: ['listo', 'ready'],
  completed: ['completado', 'completed'], cancelled: ['cancelado', 'cancelled'],
  pending: ['pendiente', 'pending'], confirmed: ['confirmado', 'confirmed'], seated: ['en curso', 'in progress'],
  done: ['completado', 'done'], out: ['entregado', 'handed out'], returned: ['devuelto', 'returned'],
};
const money = (v: unknown) => (v == null ? '' : `$${Number(v).toFixed(2)}`);
const st = (v: unknown): [string, string] => STATUS[String(v)] ?? [String(v ?? ''), String(v ?? '')];

function kindText(kind: string, d: Record<string, unknown>): { title: [string, string]; sub: [string, string] } {
  const s = (k: string) => String(d[k] ?? '');
  switch (kind) {
    case 'order_new': return { title: ['Nuevo pedido', 'New order'], sub: [`${s('code')} · ${money(d.total)}`.trim(), `${s('code')} · ${money(d.total)}`.trim()] };
    case 'order_status': { const [a, b] = st(d.status); return { title: [`Tu pedido está ${a}`, `Your order is ${b}`], sub: [s('code'), s('code')] }; }
    case 'booking_new': return { title: ['Nueva reserva', 'New booking'], sub: [s('service') || s('name'), s('service') || s('name')] };
    case 'booking_status': { const [a, b] = st(d.status); return { title: [`Tu reserva está ${a}`, `Your booking is ${b}`], sub: [s('service'), s('service')] }; }
    case 'rental_new': return { title: ['Nueva renta', 'New rental'], sub: [s('item') || s('name'), s('item') || s('name')] };
    case 'rental_status': { const [a, b] = st(d.status); return { title: [`Tu renta está ${a}`, `Your rental is ${b}`], sub: [s('item'), s('item')] }; }
    case 'message': return { title: [`Mensaje de ${s('name')}`, `Message from ${s('name')}`], sub: [s('preview'), s('preview')] };
    default: return { title: ['Notificación', 'Notification'], sub: ['', ''] };
  }
}
function relTime(iso: string): [string, string] {
  const min = Math.floor((Date.now() - new Date(iso).getTime()) / 60000);
  if (min < 1) return ['ahora', 'now'];
  if (min < 60) return [`hace ${min} min`, `${min}m`];
  const h = Math.floor(min / 60);
  if (h < 24) return [`hace ${h} h`, `${h}h`];
  const dd = Math.floor(h / 24);
  if (dd === 1) return ['ayer', '1d'];
  return [`hace ${dd} d`, `${dd}d`];
}
function groupOf(iso: string): 'hoy' | 'semana' | 'antes' {
  const d = (Date.now() - new Date(iso).getTime()) / 86400000;
  return d < 1 ? 'hoy' : d < 7 ? 'semana' : 'antes';
}
const rowToItem = (r: RawRow, read: boolean): NotifItem => {
  const m = META[r.kind] ?? { icon: 'store', color: '#6D4DF6', bg: '#EFEBFF' };
  const t = kindText(r.kind, r.data ?? {});
  return { id: r.id, icon: m.icon, color: m.color, bg: m.bg, title: t.title, sub: t.sub, group: groupOf(r.created_at), time: relTime(r.created_at), read, link: r.link || '/cuenta' };
};

type Ctx = { items: NotifItem[]; unreadCount: number; demo: boolean; markRead: (id: string) => void; markAllRead: () => void };
const NotifCtx = createContext<Ctx | null>(null);

export function NotificationsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [rows, setRows] = useState<RawRow[] | null>(null); // null → demo (logged out)
  const [readSet, setReadSet] = useState<Set<string>>(new Set());

  // load + realtime for the signed-in user
  useEffect(() => {
    if (!user || !supabase) { setRows(null); setReadSet(new Set()); return; }
    let cancelled = false;
    supabase.from('notifications').select('id,kind,data,link,read,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(60)
      .then(({ data }) => { if (!cancelled) setRows((data as RawRow[]) ?? []); });
    const ch = supabase
      .channel(`notif-${user.id}`)
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'notifications', filter: `user_id=eq.${user.id}` },
        (payload) => setRows((l) => { const r = payload.new as RawRow; return l && l.some((x) => x.id === r.id) ? l : [r, ...(l ?? [])]; }))
      .subscribe();
    return () => { cancelled = true; supabase!.removeChannel(ch); };
  }, [user?.id]);

  const items = useMemo<NotifItem[]>(() => {
    if (rows) return rows.map((r) => rowToItem(r, r.read || readSet.has(r.id)));
    // demo fixtures
    return NOTIFS.map((n) => ({
      id: n.id, icon: n.ic, color: n.color, bg: n.bg,
      title: [n.titleEs, n.titleEn], sub: [n.subEs, n.subEn], group: n.g, time: [n.timeEs, n.timeEn],
      read: !n.unread || readSet.has(n.id), link: VIEW_PATH[n.view],
    }));
  }, [rows, readSet]);

  const unreadCount = items.filter((i) => !i.read).length;

  const markRead = useCallback((id: string) => {
    setReadSet((s) => new Set(s).add(id));
    if (user && supabase && rows) supabase.from('notifications').update({ read: true }).eq('id', id).then(() => {});
  }, [user, rows]);
  const markAllRead = useCallback(() => {
    setReadSet(new Set(items.map((i) => i.id)));
    if (user && supabase && rows) supabase.from('notifications').update({ read: true }).eq('user_id', user.id).eq('read', false).then(() => {});
  }, [user, rows, items]);

  const value = useMemo<Ctx>(() => ({ items, unreadCount, demo: !rows, markRead, markAllRead }), [items, unreadCount, rows, markRead, markAllRead]);
  return <NotifCtx.Provider value={value}>{children}</NotifCtx.Provider>;
}

export function useNotifications(): Ctx {
  const ctx = useContext(NotifCtx);
  if (!ctx) throw new Error('useNotifications must be used inside <NotificationsProvider>');
  return ctx;
}
