'use client';

// In-app notifications (migration 0054). A per-user feed auto-generated by DB
// triggers on real events (orders, bookings, rentals, chat). Signed in → real
// rows + realtime; logged out → the demo fixtures so the prototype stays alive.
// Rows are language-neutral (kind + data); the localized text is built here as a
// bilingual tuple the bell/panel render via L. Consumed by NotifPanel + the bell
// badge (AppHeader / BottomNav).

import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/auth';
import { useLang } from '@/lib/i18n';
import { syncPush } from '@/lib/push';

export type NotifIcon = 'heart' | 'message' | 'calendar' | 'store' | 'user' | 'tag' | 'star';
export type NotifItem = {
  id: string;
  icon: NotifIcon;
  color: string;
  bg: string;
  title: [string, string]; // [es, en]
  sub: [string, string];
  group: 'hoy' | 'semana' | 'antes';
  time: [string, string];
  read: boolean;
  link: string;
};

type RawRow = { id: string; kind: string; data: Record<string, unknown>; link: string | null; read: boolean; created_at: string };

const META: Record<string, { icon: NotifIcon; color: string; bg: string }> = {
  order_new: { icon: 'store', color: '#6D4DF6', bg: '#EFEBFF' },
  order_status: { icon: 'store', color: '#1F8A4C', bg: '#E3F5EA' },
  booking_new: { icon: 'calendar', color: '#6D4DF6', bg: '#EFEBFF' },
  booking_status: { icon: 'calendar', color: '#1F8A4C', bg: '#E3F5EA' },
  booking_cancelled: { icon: 'calendar', color: '#D6336C', bg: '#FDE7EF' },
  booking_resched: { icon: 'calendar', color: '#B8860B', bg: '#FCF1C7' },
  rental_new: { icon: 'tag', color: '#6D4DF6', bg: '#EFEBFF' },
  rental_status: { icon: 'tag', color: '#1F8A4C', bg: '#E3F5EA' },
  ticket_new: { icon: 'calendar', color: '#6D4DF6', bg: '#EFEBFF' },
  ticket_status: { icon: 'calendar', color: '#1F8A4C', bg: '#E3F5EA' },
  review_new: { icon: 'star', color: '#B8860B', bg: '#FCF1C7' },
  review_reply: { icon: 'message', color: '#1F8A4C', bg: '#E3F5EA' },
  endorse_new: { icon: 'heart', color: '#7B61FF', bg: '#EFEBFF' },
  rsvp_new: { icon: 'user', color: '#6D4DF6', bg: '#EFEBFF' },
  event_cancelled: { icon: 'calendar', color: '#D6336C', bg: '#FDE7EF' },
  waitlist_open: { icon: 'calendar', color: '#1F8A4C', bg: '#E3F5EA' },
  message: { icon: 'message', color: '#2F6FED', bg: '#E5EFFB' },
  // Comunidad (migración 0136). Hasta 2026-08-03 la sección era muda: te
  // comentaban o te seguían y nadie te avisaba.
  comment_new: { icon: 'message', color: '#6D4DF6', bg: '#EFEBFF' },
  reply_new: { icon: 'message', color: '#2F6FED', bg: '#E5EFFB' },
  post_like: { icon: 'heart', color: '#D6336C', bg: '#FDE7EF' },
  follow_new: { icon: 'user', color: '#1F8A4C', bg: '#E3F5EA' },
};
const STATUS: Record<string, [string, string]> = {
  new: ['nuevo', 'new'], preparing: ['en preparación', 'preparing'], ready: ['listo', 'ready'],
  completed: ['completado', 'completed'], cancelled: ['cancelado', 'cancelled'],
  pending: ['pendiente', 'pending'], confirmed: ['confirmado', 'confirmed'], seated: ['en curso', 'in progress'],
  done: ['completado', 'done'], out: ['entregado', 'handed out'], returned: ['devuelto', 'returned'],
  used: ['usado', 'used'], refunded: ['reembolsado', 'refunded'], no_show: ['no asistió', 'no-show'],
};
const money = (v: unknown) => (v == null ? '' : `$${Number(v).toFixed(2)}`);
const st = (v: unknown): [string, string] => STATUS[String(v)] ?? [String(v ?? ''), String(v ?? '')];

function kindText(kind: string, d: Record<string, unknown>): { title: [string, string]; sub: [string, string] } {
  const s = (k: string) => String(d[k] ?? '');
  switch (kind) {
    case 'order_new': return { title: ['Nuevo pedido', 'New order'], sub: [`${s('code')} · ${money(d.total)}`.trim(), `${s('code')} · ${money(d.total)}`.trim()] };
    case 'order_status': {
      const from = [s('business') || s('code'), s('business') || s('code')] as [string, string];
      // STORE orders (Tienda — fulfillment.kind='store') speak Amazon: packing,
      // truck, "ready for store pickup". Food keeps the DoorDash voice.
      const store = d.kind === 'store';
      if (d.dispatch === 'assigned') return { title: ['Repartidor asignado a tu pedido', 'A driver was assigned to your order'], sub: from };
      if (d.dispatch === 'picked_up') return { title: [`${s('driver') || 'El repartidor'} recogió tu pedido`, `${s('driver') || 'Your driver'} picked up your order`], sub: from };
      if (d.dispatch === 'on_the_way') return store
        ? { title: ['¡Tu pedido va en camino! 🚚', 'Your order is on the way! 🚚'], sub: from }
        : { title: ['¡Tu pedido va en camino! 🛵', 'Your order is on the way! 🛵'], sub: from };
      if (d.dispatch === 'delivered') return { title: ['Tu pedido fue entregado ✅', 'Your order was delivered ✅'], sub: from };
      const [a, b] = st(d.status);
      if (d.status === 'preparing') return store
        ? { title: ['El negocio confirmó tu compra y está empacando tu pedido 📦', 'The business confirmed your purchase and is packing your order 📦'], sub: from }
        : { title: ['El negocio aceptó tu pedido y lo está preparando', 'The business accepted your order and is preparing it'], sub: from };
      if (d.status === 'ready') return store && d.channel !== 'delivery'
        ? { title: ['Tu pedido está listo para recoger en tienda 🛍️', 'Your order is ready for store pickup 🛍️'], sub: from }
        : { title: ['Tu pedido está listo 🎉', 'Your order is ready 🎉'], sub: from };
      return { title: [`Tu pedido está ${a}`, `Your order is ${b}`], sub: from };
    }
    case 'booking_new': {
      const who = [s('service'), s('name')].filter(Boolean).join(' · ');
      // pending → needs the owner's approval; confirmed → auto-confirmed booking
      return d.status === 'pending'
        ? { title: ['Nueva solicitud de cita 📅', 'New booking request 📅'], sub: [who, who] }
        : { title: ['Nueva reserva 📅', 'New booking 📅'], sub: [who, who] };
    }
    case 'booking_status': {
      const svc = [s('service'), s('service')] as [string, string];
      if (d.status === 'confirmed') return { title: ['¡Tu cita está confirmada! 📅', 'Your appointment is confirmed! 📅'], sub: svc };
      if (d.status === 'cancelled') return { title: ['Tu cita fue cancelada', 'Your appointment was cancelled'], sub: svc };
      if (d.status === 'no_show') return { title: ['Se marcó que no asististe a tu cita', 'You were marked as a no-show'], sub: svc };
      if (d.status === 'seated') return { title: ['Tu cita está en curso', 'Your appointment is in progress'], sub: svc };
      if (d.status === 'done') return { title: ['¡Gracias por tu visita! ⭐', 'Thanks for coming in! ⭐'], sub: svc };
      const [a, b] = st(d.status);
      return { title: [`Tu reserva está ${a}`, `Your booking is ${b}`], sub: svc };
    }
    case 'review_new': {
      // owner-facing: a customer left a review. sub = "N★ · Name"
      const stars = '★'.repeat(Math.max(1, Math.min(5, Number(d.rating) || 5)));
      const who = [`${stars} · ${s('name')}`, `${stars} · ${s('name')}`] as [string, string];
      return { title: ['Nueva reseña ⭐', 'New review ⭐'], sub: who };
    }
    case 'review_reply': {
      // customer-facing: the business responded to their review
      const biz = [s('business'), s('business')] as [string, string];
      return { title: ['Respondieron tu reseña 💬', 'Your review got a reply 💬'], sub: biz };
    }
    case 'booking_cancelled': {
      const who = [s('service'), s('name')].filter(Boolean).join(' · ');
      return { title: ['Reserva cancelada por el cliente', 'Booking cancelled by the client'], sub: [who, who] };
    }
    case 'booking_resched': {
      const who = [s('service'), s('name')].filter(Boolean).join(' · ');
      return { title: ['El cliente reagendó su cita', 'The client rescheduled their appointment'], sub: [who, who] };
    }
    case 'rental_new': {
      const n = Number(d.count) || 1;
      const what = n > 1 ? `${s('item')} +${n - 1} · ${s('name')}` : `${s('item') || s('name')}`;
      return d.status === 'pending'
        ? { title: ['Nueva solicitud de renta 📦', 'New rental request 📦'], sub: [what, what] }
        : { title: ['Nueva renta 📦', 'New rental 📦'], sub: [what, what] };
    }
    case 'rental_status': { const [a, b] = st(d.status); return { title: [`Tu renta está ${a}`, `Your rental is ${b}`], sub: [s('item'), s('item')] }; }
    case 'endorse_new': return { title: ['Nueva recomendación 👍', 'New recommendation 👍'], sub: [`${s('name')} te recomendó`, `${s('name')} recommended you`] };
    case 'ticket_new': return { title: ['Boletos vendidos', 'Tickets sold'], sub: [`${s('event')} · ${s('qty')} · ${s('name')}`, `${s('event')} · ${s('qty')} · ${s('name')}`] };
    case 'ticket_status': { const [a, b] = st(d.status); return { title: [`Tu boleto: ${a}`, `Your ticket: ${b}`], sub: [s('event'), s('event')] }; }
    case 'rsvp_new': return { title: ['Nuevo asistente', 'New attendee'], sub: [s('event'), s('event')] };
    case 'event_cancelled': return { title: ['Evento cancelado', 'Event cancelled'], sub: [s('event'), s('event')] };
    case 'waitlist_open': return { title: ['¡Se liberó un lugar!', 'A spot opened up!'], sub: [s('event'), s('event')] };
    case 'message': return { title: [`Mensaje de ${s('name')}`, `Message from ${s('name')}`], sub: [s('preview'), s('preview')] };
    // ── Comunidad ──
    case 'comment_new': return { title: [`${s('name')} comentó tu publicación`, `${s('name')} commented on your post`], sub: [s('preview'), s('preview')] };
    case 'reply_new':   return { title: [`${s('name')} te respondió`, `${s('name')} replied to you`], sub: [s('preview'), s('preview')] };
    case 'post_like':   return { title: [`A ${s('name')} le gustó tu publicación`, `${s('name')} liked your post`], sub: [s('preview'), s('preview')] };
    case 'follow_new':  return { title: [`${s('name')} te sigue`, `${s('name')} is following you`], sub: ['Ahora ve tus publicaciones en su inicio', 'They now see your posts in their feed'] };
    default: return { title: ['Notificación', 'Notification'], sub: ['', ''] };
  }
}
function relTime(iso: string): [string, string] {
  const min = Math.floor((Date.now() - new Date(iso).getTime()) / 60000);
  if (min < 1) return ['ahora', 'now'];
  if (min < 60) return [`hace ${min} min`, `${min}m`];
  const h = Math.floor(min / 60);
  if (h < 24) return [`hace ${h} h`, `${h}h`];
  const dd = Math.floor(h / 24);
  if (dd === 1) return ['ayer', '1d'];
  return [`hace ${dd} d`, `${dd}d`];
}
function groupOf(iso: string): 'hoy' | 'semana' | 'antes' {
  const d = (Date.now() - new Date(iso).getTime()) / 86400000;
  return d < 1 ? 'hoy' : d < 7 ? 'semana' : 'antes';
}
const rowToItem = (r: RawRow, read: boolean): NotifItem => {
  const m = META[r.kind] ?? { icon: 'store', color: '#6D4DF6', bg: '#EFEBFF' };
  const t = kindText(r.kind, r.data ?? {});
  return { id: r.id, icon: m.icon, color: m.color, bg: m.bg, title: t.title, sub: t.sub, group: groupOf(r.created_at), time: relTime(r.created_at), read, link: r.link || '/cuenta' };
};

type Ctx = {
  items: NotifItem[]; unreadCount: number; demo: boolean;
  /** La consulta falló (no es lo mismo que «no tienes avisos»). */
  failed: boolean;
  /** Hay más de los que se han traído: la insignia usa el total real. */
  hasMore: boolean;
  loadingMore: boolean;
  loadMore: () => void;
  markRead: (id: string) => void; markAllRead: () => void;
};
/** Cuántas se traen por página. Antes eran 60 fijas y no había forma de ver la 61. */
const PAGE = 40;

const NotifCtx = createContext<Ctx | null>(null);

export function NotificationsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const { lang } = useLang();
  const [rows, setRows] = useState<RawRow[] | null>(null); // null → demo (logged out)
  const [readSet, setReadSet] = useState<Set<string>>(new Set());
  // Un fallo de la consulta NO es una campana vacía. Antes se descartaba el
  // `error` y «no se pudo cargar» se pintaba igual que «todo al día» — el
  // usuario se quedaba sin saber que le habían escrito. (2ª auditoría.)
  const [failed, setFailed] = useState(false);
  // El total REAL de no leídos, contado en la base. La insignia se calculaba
  // sobre las 60 traídas: con 119 sin leer, decía 57.
  const [unreadTotal, setUnreadTotal] = useState(0);
  const [total, setTotal] = useState(0);
  const [loadingMore, setLoadingMore] = useState(false);

  // If this device already granted push, refresh its stored subscription on login
  // (endpoints rotate) so send-push keeps reaching it. Silent no-op otherwise.
  useEffect(() => { if (user) void syncPush(lang); }, [user?.id, lang]);

  // load + realtime for the signed-in user
  useEffect(() => {
    if (!user || !supabase) { setRows(null); setReadSet(new Set()); setFailed(false); return; }
    let cancelled = false;
    setFailed(false);
    void (async () => {
      const [page, unread, all] = await Promise.all([
        supabase!.from('notifications').select('id,kind,data,link,read,created_at')
          .eq('user_id', user.id).order('created_at', { ascending: false }).limit(PAGE),
        supabase!.from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', user.id).eq('read', false),
        supabase!.from('notifications').select('id', { count: 'exact', head: true }).eq('user_id', user.id),
      ]);
      if (cancelled) return;
      if (page.error) { setFailed(true); setRows([]); return; }
      setRows((page.data as RawRow[]) ?? []);
      setUnreadTotal(unread.count ?? 0);
      setTotal(all.count ?? 0);
    })();
    const ch = supabase
      .channel(`notif-${user.id}`)
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'notifications', filter: `user_id=eq.${user.id}` },
        (payload) => setRows((l) => {
          const r = payload.new as RawRow;
          if (l && l.some((x) => x.id === r.id)) return l;
          setUnreadTotal((n) => n + 1);
          setTotal((n) => n + 1);
          return [r, ...(l ?? [])];
        }))
      .subscribe();
    return () => { cancelled = true; supabase!.removeChannel(ch); };
  }, [user?.id]);

  const items = useMemo<NotifItem[]>(() => {
    // Real notifications only. Guests / not-yet-loaded state = empty (never the
    // NOTIFS demo fixtures presented as real, with a fake unread badge — rule #8).
    if (rows) return rows.map((r) => rowToItem(r, r.read || readSet.has(r.id)));
    return [];
  }, [rows, readSet]);

  // El total sale de la base; se le restan los que se han marcado leídos en esta
  // sesión y que ya estaban traídos.
  const leidosAhora = items.filter((i) => readSet.has(i.id) && !rows?.find((r) => r.id === i.id)?.read).length;
  const unreadCount = Math.max(0, unreadTotal - leidosAhora);
  const hasMore = !!rows && rows.length < total;

  const loadMore = useCallback(() => {
    if (!user || !supabase || !rows || loadingMore) return;
    setLoadingMore(true);
    void supabase.from('notifications').select('id,kind,data,link,read,created_at')
      .eq('user_id', user.id).order('created_at', { ascending: false })
      .range(rows.length, rows.length + PAGE - 1)
      .then(({ data, error }) => {
        setLoadingMore(false);
        if (error || !Array.isArray(data)) return;
        setRows((l) => {
          const vistos = new Set((l ?? []).map((x) => x.id));
          return [...(l ?? []), ...(data as RawRow[]).filter((r) => !vistos.has(r.id))];
        });
      });
  }, [user, rows, loadingMore]);

  const markRead = useCallback((id: string) => {
    setReadSet((s) => new Set(s).add(id));
    if (user && supabase && rows) supabase.from('notifications').update({ read: true }).eq('id', id).then(() => {});
  }, [user, rows]);
  const markAllRead = useCallback(() => {
    setReadSet(new Set(items.map((i) => i.id)));
    setUnreadTotal(0);
    if (user && supabase && rows) supabase.from('notifications').update({ read: true }).eq('user_id', user.id).eq('read', false).then(() => {});
  }, [user, rows, items]);

  const value = useMemo<Ctx>(
    () => ({ items, unreadCount, demo: !rows, failed, hasMore, loadingMore, loadMore, markRead, markAllRead }),
    [items, unreadCount, rows, failed, hasMore, loadingMore, loadMore, markRead, markAllRead],
  );
  return <NotifCtx.Provider value={value}>{children}</NotifCtx.Provider>;
}

export function useNotifications(): Ctx {
  const ctx = useContext(NotifCtx);
  if (!ctx) throw new Error('useNotifications must be used inside <NotificationsProvider>');
  return ctx;
}
